CREATE TABLE MY_EVENTS (
    NAME VARCHAR(100) NOT NULL,
    DATE_ADDED VARCHAR(50),
    START_TIME VARCHAR(20),
    CATEGORY VARCHAR(50),
    PRICE VARCHAR(30),
    LOCATION VARCHAR(100),
    BYU_ID VARCHAR(100),
    DESCRIPTION VARCHAR(3000),
    DAY_OF_WEEK VARCHAR(20),
    URL VARCHAR(1000),
    CONSTRAINT PRIMARY_KEY PRIMARY KEY (BYU_ID, START_TIME, NAME)

);

CREATE TABLE EVENT_TABLE (
    NAME VARCHAR(100) NOT NULL,
    START_TIME VARCHAR(20) NOT NULL,
    PRICE VARCHAR(30),
    DESCRIPTION VARCHAR(3000),
    URL VARCHAR(1000),
    LOCATION VARCHAR(100),
    DAY_OF_WEEK VARCHAR(20),
    BYU_ID VARCHAR(200),
    CATEGORY VARCHAR(50),
    CONSTRAINT MY_KEY PRIMARY KEY (BYU_ID, START_TIME, NAME)

);


